In [ ]:
단원별 심화 연습 문제 - 혼자 못 품
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns
import glob
​
# set floating point formatting
pd.options.display.float_format = '{:,.1f}'.format
Q4
범위

(이전 범위 포함)
groupby(), pivot_table()
# 데이터셋
taxis = sns.load_dataset('taxis')
taxis.head()
pickup	dropoff	passengers	distance	fare	tip	tolls	total	color	payment	pickup_zone	dropoff_zone	pickup_borough	dropoff_borough
0	2019-03-23 20:21:09	2019-03-23 20:27:24	1	1.6	7.0	2.1	0.0	12.9	yellow	credit card	Lenox Hill West	UN/Turtle Bay South	Manhattan	Manhattan
1	2019-03-04 16:11:55	2019-03-04 16:19:00	1	0.8	5.0	0.0	0.0	9.3	yellow	cash	Upper West Side South	Upper West Side South	Manhattan	Manhattan
2	2019-03-27 17:53:01	2019-03-27 18:00:25	1	1.4	7.5	2.4	0.0	14.2	yellow	credit card	Alphabet City	West Village	Manhattan	Manhattan
3	2019-03-10 01:23:59	2019-03-10 01:49:51	1	7.7	27.0	6.2	0.0	37.0	yellow	credit card	Hudson Sq	Yorkville West	Manhattan	Manhattan
4	2019-03-30 13:27:42	2019-03-30 13:37:14	3	2.2	9.0	1.1	0.0	13.4	yellow	credit card	Midtown East	Yorkville West	Manhattan	Manhattan
taxis 데이터에서 요일별 distance의 평균을 산출하세요 (DataFrame 형식으로 출력하세요)

[참고] 0: 월요일 ~ 6: 일요일
taxis.info() #인포 먼저 확인하고, 요일로 변환
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64         
 3   distance         6433 non-null   float64       
 4   fare             6433 non-null   float64       
 5   tip              6433 non-null   float64       
 6   tolls            6433 non-null   float64       
 7   total            6433 non-null   float64       
 8   color            6433 non-null   object        
 9   payment          6389 non-null   object        
 10  pickup_zone      6407 non-null   object        
 11  dropoff_zone     6388 non-null   object        
 12  pickup_borough   6407 non-null   object        
 13  dropoff_borough  6388 non-null   object        
dtypes: datetime64[ns](2), float64(5), int64(1), object(6)
memory usage: 703.7+ KB
# 코드를 입력해 주세요
pd.to_datetime(taxis['pickup']) #몰랐음...
0      2019-03-23 20:21:09
1      2019-03-04 16:11:55
2      2019-03-27 17:53:01
3      2019-03-10 01:23:59
4      2019-03-30 13:27:42
               ...        
6428   2019-03-31 09:51:53
6429   2019-03-31 17:38:00
6430   2019-03-23 22:55:18
6431   2019-03-04 10:09:25
6432   2019-03-13 19:31:22
Name: pickup, Length: 6433, dtype: datetime64[ns]
 taxis.groupby('dayofweek')['distance'].mean().reset_index()
taxis['dayofweek'] = taxis['pickup'].dt.dayofweek
​
tmp = taxis.groupby('dayofweek')['distance'].mean().reset_index()
tmp
dayofweek	distance
0	0	3.2
1	1	3.0
2	2	3.1
3	3	3.0
4	4	2.9
5	5	2.9
6	6	3.0
[출력 결과]

dayofweek	distance
0	0	3.2
1	1	3.0
2	2	3.1
3	3	3.0
4	4	2.9
5	5	2.9
6	6	3.0
위에서 산출한 통계를 바탕으로 다음을 도출합니다.

요일별 distance의 평균 값을 구하였습니다.
구한 평균치보다 작은(미만) 인 데이터만 추출하세요.
(예시) 0: 월요일 평균 distance가 3.215971이라면 3.215971보다 작은 데이터만 추출합니다. (월~ 일요일까지 모두 적용)
필터 후 distance, fare, tip에 대한 중앙값(median)과 표준편차(std)를 산출합니다.
# 코드를 입력해 주세요
tmp
dayofweek	distance
0	0	3.2
1	1	3.0
2	2	3.1
3	3	3.0
4	4	2.9
5	5	2.9
6	6	3.0
taxis.head()
pickup	dropoff	passengers	distance	fare	tip	tolls	total	color	payment	pickup_zone	dropoff_zone	pickup_borough	dropoff_borough	dayofweek
0	2019-03-23 20:21:09	2019-03-23 20:27:24	1	1.6	7.0	2.1	0.0	12.9	yellow	credit card	Lenox Hill West	UN/Turtle Bay South	Manhattan	Manhattan	5
1	2019-03-04 16:11:55	2019-03-04 16:19:00	1	0.8	5.0	0.0	0.0	9.3	yellow	cash	Upper West Side South	Upper West Side South	Manhattan	Manhattan	0
2	2019-03-27 17:53:01	2019-03-27 18:00:25	1	1.4	7.5	2.4	0.0	14.2	yellow	credit card	Alphabet City	West Village	Manhattan	Manhattan	2
3	2019-03-10 01:23:59	2019-03-10 01:49:51	1	7.7	27.0	6.2	0.0	37.0	yellow	credit card	Hudson Sq	Yorkville West	Manhattan	Manhattan	6
4	2019-03-30 13:27:42	2019-03-30 13:37:14	3	2.2	9.0	1.1	0.0	13.4	yellow	credit card	Midtown East	Yorkville West	Manhattan	Manhattan	5
def is_small(x):
    return x['distance'] < tmp.loc[x['dayofweek'], 'distance']
cond1 = taxis.apply(is_small, axis=1)
cond1
0        True
1        True
2        True
3       False
4        True
        ...  
6428     True
6429    False
6430    False
6431     True
6432    False
Length: 6433, dtype: bool
cond2 = (taxis['passengers'] <= 2)
taxis.loc[cond1&cond2, ['distance', 'fare', 'tip']].agg(['median', 'std'])
distance	fare	tip
median	1.2	7.5	1.6
std	0.7	4.7	1.4
[출력 결과]

distance	fare	tip
median	1.2	7.5	1.6
std	0.7	4.7	1.4
다음의 피벗테이블을 완성해 주세요

passengers 2명 이하로 탑승한 데이터에 대하여 요일(dayofweek)과 payment 별 fare의 중앙값(median)과 표준편차(std)를 산출합니다.
# 코드를 입력해 주세요
taxis.groupby(['dayofweek', 'payment'])['fare'].agg(['median','std'])
#groupby 꼭 적어줘야 하고, groupby는 통계량 필요함.
cond = (taxis['passengers'] <= 2)
taxis.loc[cond].pivot_table(index = 'dayofweek', columns = 'payment', values ='fare', aggfunc = ['median', 'std'])
median	std
payment	cash	credit card	cash	credit card
dayofweek				
0	8.8	9.5	13.3	12.4
1	8.0	10.0	12.4	12.4
2	8.5	9.5	10.1	11.2
3	8.5	10.0	9.2	11.3
4	8.0	9.5	8.6	11.9
5	9.0	9.5	8.6	11.0
6	8.0	9.5	13.3	11.0
[출력 결과]

median	std
payment	cash	credit card	cash	credit card
dayofweek				
0	8.8	9.5	13.3	12.4
1	8.0	10.0	12.4	12.4
2	8.5	9.5	10.1	11.2
3	8.5	10.0	9.2	11.3
4	8.0	9.5	8.6	11.9
5	9.0	9.5	8.6	11.0
6	8.0	9.5	13.3	11.0
제출
제출을 위해 새로 로드된 택시 데이터셋에서 요일별 distance의 평균을 계산한 결과를 DataFrame 형식으로 result_df에 저장하세요.

taxis = sns.load_dataset('taxis')
​
taxis['dayofweek'] = taxis['pickup'].dt.dayofweek
​
result_df = taxis.groupby('dayofweek')['distance'].mean().reset_index()
result_df
dayofweek	distance
0	0	3.2
1	1	3.0
2	2	3.1
3	3	3.0
4	4	2.9
5	5	2.9
6	6	3.0
채점 수행
아래 코드는 채점 수행을 위한 코드입니다.

따라서 이를 수정했을시 채점이 제대로 이루어지지 않습니다.

주의: 채점 코드를 실행하기 전에 반드시 코드 파일을 한번 저장하시길 바랍니다.

import os
​
result_df.to_json('result.json')
​
os.system('elice_grade result.json cds_ds_exercise.ipynb')
send files ['result.json', 'cds_ds_exercise.ipynb'] for grade...
waiting result...
waiting result...
waiting result...
done!

Score: 100.000000
Duration: 2.217 seconds
=== Message ===
제출 완료되었습니다.
0
​